{{- if .Values.api_proxy.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api_proxy.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-api-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}-api-proxy
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "chart" . }}
spec:
  type: {{ .Values.api_proxy.service.type }}
  ports:
    - port: {{ .Values.api_proxy.service.port }}
      targetPort: rest-api
      protocol: TCP
      name: rest-api
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-api-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}-api-proxy
{{- end }}