{{- if .Values.api_proxy.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api_proxy.deployment.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-rest-api
    app.kubernetes.io/instance: {{ .Release.Name }}-rest-api
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "chart" . }}
spec:
  replicas: {{ .Values.api_proxy.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-rest-api
      app.kubernetes.io/instance: {{ .Release.Name }}-rest-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-rest-api
        app.kubernetes.io/instance: {{ .Release.Name }}-rest-api
    spec:
      {{- with .Values.api_proxy.deployment.serviceAccount }}
      serviceAccountName: {{ . | quote }}
      {{- end }}
      {{- with .Values.api_proxy.deployment.image.pullSecrets }}
      imagePullSecrets:
      {{ toYaml . | nindent 6 }}
      {{- end }}
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
      containers:
        - name: bitflow-api-proxy
          image: "{{ .Values.api_proxy.deployment.image.repository }}"
          imagePullPolicy: "{{ .Values.api_proxy.deployment.image.pullPolicy }}"
          args: [ "-l", ":{{ .Values.api_proxy.deployment.port }}" ]
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
          ports:
            - name: rest-api
              containerPort: {{ .Values.api_proxy.deployment.port }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api_proxy.deployment.port }}
            periodSeconds: {{ .Values.api_proxy.deployment.livenessProbePeriod }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api_proxy.deployment.port }}
            periodSeconds: {{ .Values.api_proxy.deployment.readinessProbeDelay }}
          resources:
            {{- toYaml .Values.api_proxy.resources | nindent 12 }}

      {{- with .Values.api_proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api_proxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api_proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}