apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitflow
rules:
  - apiGroups: [ "bitflow.com" ]
    resources: [ "*" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ pods, configmaps ]
    verbs: [ "*" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bitflow
subjects:
  - kind: ServiceAccount
    name: bitflow
roleRef:
  kind: Role
  name: bitflow
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bitflow
rules:
  - apiGroups: [ "" ]
    resources: [ nodes ]
    verbs: [ "*" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bitflow
subjects:
  - kind: ServiceAccount
    name: bitflow
    # Unfortunately, this explicit namespace reference is required, and must be adjusted manually when deploying in a different namespace
    namespace: default
roleRef:
  kind: ClusterRole
  name: bitflow
  apiGroup: rbac.authorization.k8s.io
---
# This extra set of permissions is required to enable the operator monitoring service, which is optional
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitflow-monitoring
rules:
  - apiGroups: [ "" ]
    resources: [ services ]
    verbs: [ "*" ]
  - apiGroups: [ "apps" ]
    resources: [ replicasets, deployments ]
    verbs: [ "*" ]
  - apiGroups: [ "monitoring.coreos.com" ]
    resources: [ servicemonitors ]
    verbs: [ "*" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bitflow-monitoring
subjects:
  - kind: ServiceAccount
    name: bitflow
roleRef:
  kind: Role
  name: bitflow-monitoring
  apiGroup: rbac.authorization.k8s.io
