apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitflow
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bitflow
subjects:
  - kind: ServiceAccount
    name: bitflow
roleRef:
  kind: Role
  name: bitflow
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitflow
rules:
  - apiGroups: [ "" ]
    resources: [ pods, services, services/finalizers, endpoints, persistentvolumeclaims, events, configmaps, secrets ]
    verbs: [ "*" ]

  - apiGroups: [ apps ]
    resources: [ deployments, daemonsets, replicasets, statefulsets ]
    verbs: [ "*" ]

  - apiGroups: [ "monitoring.coreos.com" ]
    resources: [ servicemonitors ]
    verbs: [ "get", "create" ]

  - apiGroups: [ apps ]
    resourceNames: [ "bitflow" ]
    resources: [ "deployments/finalizers" ]
    verbs: [ update ]

  - apiGroups: [ "" ]
    resources: [ pods ]
    verbs: [ get ]

  - apiGroups: [ apps ]
    resources: [ replicasets ]
    verbs: [ get ]

  - apiGroups: [ "bitflow.com" ]
    resources: [ "*", "bitflowsources", "bitflowsteps" ]
    verbs: [ "*" ]
