// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitflowSource) DeepCopyInto(out *BitflowSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitflowSource.
func (in *BitflowSource) DeepCopy() *BitflowSource {
	if in == nil {
		return nil
	}
	out := new(BitflowSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitflowSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitflowSourceList) DeepCopyInto(out *BitflowSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitflowSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitflowSourceList.
func (in *BitflowSourceList) DeepCopy() *BitflowSourceList {
	if in == nil {
		return nil
	}
	out := new(BitflowSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitflowSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitflowSourceSpec) DeepCopyInto(out *BitflowSourceSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitflowSourceSpec.
func (in *BitflowSourceSpec) DeepCopy() *BitflowSourceSpec {
	if in == nil {
		return nil
	}
	out := new(BitflowSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitflowStep) DeepCopyInto(out *BitflowStep) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitflowStep.
func (in *BitflowStep) DeepCopy() *BitflowStep {
	if in == nil {
		return nil
	}
	out := new(BitflowStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitflowStep) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitflowStepList) DeepCopyInto(out *BitflowStepList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BitflowStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitflowStepList.
func (in *BitflowStepList) DeepCopy() *BitflowStepList {
	if in == nil {
		return nil
	}
	out := new(BitflowStepList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BitflowStepList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitflowStepSpec) DeepCopyInto(out *BitflowStepSpec) {
	*out = *in
	if in.Ingest != nil {
		in, out := &in.Ingest, &out.Ingest
		*out = make([]*IngestMatch, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(IngestMatch)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]*StepOutput, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(StepOutput)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MinResources != nil {
		in, out := &in.MinResources, &out.MinResources
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(corev1.Pod)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitflowStepSpec.
func (in *BitflowStepSpec) DeepCopy() *BitflowStepSpec {
	if in == nil {
		return nil
	}
	out := new(BitflowStepSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BitflowValidationStatus) DeepCopyInto(out *BitflowValidationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BitflowValidationStatus.
func (in *BitflowValidationStatus) DeepCopy() *BitflowValidationStatus {
	if in == nil {
		return nil
	}
	out := new(BitflowValidationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngestMatch) DeepCopyInto(out *IngestMatch) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngestMatch.
func (in *IngestMatch) DeepCopy() *IngestMatch {
	if in == nil {
		return nil
	}
	out := new(IngestMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepOutput) DeepCopyInto(out *StepOutput) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.parsedUrl != nil {
		out.parsedUrl = DeepCopyUrl(in.parsedUrl)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepOutput.
func (in *StepOutput) DeepCopy() *StepOutput {
	if in == nil {
		return nil
	}
	out := new(StepOutput)
	in.DeepCopyInto(out)
	return out
}
