
controller:
  deployment:
    enabled: true
    name: bitflow-controller
    serviceAccount: bitflow
    port: 8888
    livenessProbePeriod: 600
    readinessProbeDelay: 5
    image:
      repository: bitflowstream/bitflow-controller:latest
      pullPolicy: Always
      pullSecrets: []
    config:
      concurrent_reconcile: 1
      pod_id_labels: "controller=bitflow"
      record_statistics: "true"
    replicaCount: 1
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  service:
    enabled: true
    name: bitflow-controller
    type: ClusterIP
    port: 8888

  crds:
    enabled: true

  configmap:
    name: bitflow-controller-config
    enabled: true
    data:
      external.source.label: "bitflow-nodename"
      resource.limit.slots: "10"
      resource.limit.slots.grow: "2"
      resource.limit: "1.0"
      resource.limit.node.annotation: "bitflow-resource-limit"
      extra.env: "" # comma-separated list: a=b,x=y
      delete.grace.period: "15s"
      pod.spawn.period: "3s"
      reconcile.heartbeat: "30s"
      scheduler: "least-occupied"

api_proxy:
  deployment:
    enabled: true
    name: bitflow-api-proxy
    serviceAccount: bitflow
    port: 8080
    livenessProbePeriod: 60
    readinessProbeDelay: 5
    image:
      repository: bitflowstream/bitflow-api-proxy:latest
      pullPolicy: Always
      pullSecrets: []
    replicaCount: 1
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  service:
    enabled: true
    name: bitflow-api-proxy
    type: ClusterIP
    port: 8080
